### PR TITLE
Simplify log tweeting

### LINKED ISSUE #174: Recording a Tweet is unintuitive
Last night at the first trial of the tool, we didn't collect any tweet events, which was strange. 

After some investigation and another user trial, I've determined it's because clicking "Send Tweet" doesn't log the event, but "Done Tweeting" does. Not a single person on our trial last night clicked "Done Tweeting", so no events were received. 

The fix to this is to record the action on "Send Tweet", and treat that button as the advancement to the next step (which means it will happen in the background while the user is interacting with Twitter).

### PR DESCRIPTION
**Pull request by jacknugent**
Before: You must click "Send Tweet" and then "Done Tweeting" to move to next step
Now: You just need to click "Send Tweet" to progress to next step

Closes #174

### CODE REVIEW

**Comment by jacknugent** [comment]
One issue -- with this change, we lose the smooth scroll to the next step, because after clicking "Send Tweet", we open a new tab, and then scrolling is disabled on the page. So when a user returns to the app, they are still on the Tweeting step, like this:
image

So the user will have to scroll down (to "Join Our Mission" currently) themselves. If this is a big concern, I could maybe try something hack-y like setting a .5 second timer when they return to the page which then scrolls them down, or maybe this method is preferred, since it might be jarring to have the page jump as soon as you return to it.

**Comment by kevincianfarini** [comment]
@jacknugent maybe a good middle ground is to just have the log event when a user clicks `Send Tweet`, but to advance to the next step users must still explicitly press `Done Tweeting`.

**Comment by jacknugent** [comment]
> @jacknugent maybe a good middle ground is to just have the log event when a user clicks `Send Tweet`, but to advance to the next step users must still explicitly press `Done Tweeting`.

This is the current behavior

**Comment by jacknugent** [comment]
Done

**Review by EvanHahn — APPROVED** [review]

**Review by kevincianfarini — APPROVED** [review]

**Pull request merged**
